### ISSUE TITLE
Callback for (re)connects

### ISSUE THREAD

**Issue by h4cc** [Azolo/websockex#12]
When `:reconnect` was returned by `handle_disconnect` or `handle_connect_failure` there is currently no way to know when the connection was established again.

Having a new optional callback like this could help:
```elixir
      @doc false
      def handle_connect(_conn, state) do
        {:ok, state}
      end
```

My workaround for now is using `handle_frame` which is not very reliable.

**Comment by Azolo** [comment]
That's not a bad idea.

Right now, `init/2` is called after the initial connection is established.

Do you see any reason to keep the `init/2` callback with the `handle_connect/2` callback?

**Comment by h4cc** [comment]
Typically `init/2` is intended to do/start other needed processes, so its needed. Also its common to have that callback so i would not remove it.

Having a `handle_connect/2` callback looks just in the current implementation like a duplicate `init/2` but it isnt. It could be used to start things like Ping/Pong or own periodic message sending.

-------------------

Maybe some background how i use this library:

My application needs to create multiple dynamic websocket connections to other systems. If one of these connections fails, it is not considered a error and crashing is not intended, the network and remote systems are not reliable. Using a supervisor for a reconnect strategy does not apply for "let it crash" because handling connection problems is explicitly needed.

The current behaviour of a Websockex.Client is to block on `start_link` till a connection is established, which is problematic because that will also block the supervisor starting the process. Having 10 websockets that fail all at once could pile up the supervisor.

In case there is a disconnect, a reconnect will block till the connection is established again.
Using `send_frame` while a reconnect is done, there is no guarantee it was really send which is also a problem.

What i would wish to use would be something like this:

* Connection will be established after `init/2` was called, so no blocking is done in `start_link`. (This could be configured maybe to allow a blocking strategy too).
* The connection state is explicit available (:connecting, :connected, ...), maybe stored in Conn struct. It also needs to be available for external processes.
* Sending a message with `send_frame` could return ` {:error, :not_connected}` depending on connection state.
* Sending a message with `send_frame` could work in a blocking way if intended by a option or such.
* Having callbacks for connect and disconnect, so the rest of my system can react/log these incidents.
* While a re/connection is done, the Client should stay available for messages. So the blocking functions like `gen_tcp.connect` could executed in a process spawned just for that.

For now i tried to write a wrapper around a Websockex.Client, to avoid some of these problems, but that will not eliminate them. If there is not such a handling available, i will need to write a own implementation.

**Comment by Azolo** [comment]
Awesome feedback @h4cc! Thanks so much for taking the time to give your feedback. First of all, I'm still fleshing out what `WebSockex` is and isn't. I think my initial plan was to have a library what could be linked to a `GenServer` where most of the logic would happen.

What happened is that I realized that much of the functionality I wanted was super simple and could be done in a way that didn't block the underlying WebSocket for more than a millisecond. So right now my goal is to build a library that can be used easily for simple needs and then built as an under another process for complex needs.

> Typically `init/2` is intended to do/start other needed processes, so its needed. Also its common to have that callback so i would not remove it.
Having a `handle_connect/2` callback looks just in the current implementation like a duplicate `init/2` but it isnt. It could be used to start things like Ping/Pong or own periodic message sending.

> Connection will be established after init/2 was called, so no blocking is done in start_link. (This could be configured maybe to allow a blocking strategy too).

So, I have good news and bad news. The good news is that I added an `:async` option so that connecting wouldn't block.

The bad news is... I ended up making the decision to remove `init/2` in favor of `handle_connect/2` in #13. There's currently nothing that `init/2` could do that `handle_connect/2` can't and I didn't want to change `init/2` to be called before establishing the connection. I don't really like the idea of doing a lot of work before the connection.

One thing I will probably do is allow a `WebSockex.Conn` struct to be used instead of a _url_ in `start/4` and `start_link/4`.

> Having callbacks for connect and disconnect, so the rest of my system can react/log these incidents.

This is definitely something that I am going to implement.

> The connection state is explicit available (:connecting, :connected, ...), maybe stored in Conn struct. It also needs to be available for external processes.

> While a re/connection is done, the Client should stay available for messages. So the blocking functions like `gen_tcp.connect` could executed in a process spawned just for that.

🤔 I'm not sure about this one. I see the benefit, but I feel like it isn't the direction I want to go in. If I did do this it would be in another module/package. Maybe something like `WebSockexServer`! But the point is, I would rather do this in a wrapper around a `WebSockex` process.

If it ends up that required functionality absolutely can't be implemented without this, then I would approach that then.

> Sending a message with `send_frame` could return `{:error, :not_connected}` depending on connection state.
> Sending a message with `send_frame` could work in a blocking way if intended by a option or such.

A synchronous frame sending mechanism would indeed be a good idea, this is something I will think about and approach. But I may settle on an option to notify that a frame has been successfully sent.

> For now i tried to write a wrapper around a Websockex.Client, to avoid some of these problems, but that will not eliminate them. If there is not such a handling available, i will need to write a own implementation.

My goal is to build something simple that exposes all the essential functionality, then let you build something complex on top of it.

But, I get understand if WebSockex doesn't fit your needs. A lot of the functionality you want is something that I don't necessarily want to build or try to support. I want to build something useful for people, but all the code that is written is code I have to maintain.

If you do end up having to write your own implementation let me know. I could probably save you a lot of time by splitting the `Frame` module into it's own library.
