### ISSUE TITLE
Synchronous send/receive

### ISSUE THREAD

**Issue by eonpatapon** [Azolo/websockex#39]
I want to make send_frame synchronous in the sense that I want to block until I get the server response for the request, not just the frame sending ack.

The frame contains a json with a requestId UUID and the server respond with the same requestId.

With GenServer I could do something like that: https://elixirforum.com/t/wrap-async-process-for-genserver-call/2248/3. Do you think something similar is possible with your process ?

**Comment by Azolo** [comment]
No, it's not.

It's mainly because of how WebSockets work, but even if it were possible I as the maintainer don't want to approach that kind of functionality. There are two many cases where someone could want something like that and programming for just one seems like a really bad idea.

My suggestion is to start a WebSockex process from a GenServer and then write the parsing and encoding of messages in the WebSockex implementation and put your logic in the GenServer.

That way you could do a call to the GenServer and then reply when you get the message back from the WebSocket.
