### ISSUE TITLE
Allow access to server response headers after connecting

### ISSUE THREAD

**Issue by queer** [Azolo/websockex#41]
For example, when connecting to a WS server behind CloudFlare, CloudFlare appends some extra headers to the response, such as `cf-ray`; it'd be nice to be able to be able to "see" these. I would file a PR, but I'm not really certain what the best way to do this would be :<

**Comment by Azolo** [comment]
Ironically, I was sure it did this in the `handle_connect/2` callback. But you're totally right it doesn't.

The good news it's actually a pretty easy fix, because we are already grabbing and decoding the headers to [validate that we are upgrading to a WebSocket properly][1].

The bad news is, I've had a lot on my plate and feel like I've been neglecting this library 😢.

Basically, if you wanted to add a `resp_headers` field to [the `Conn` struct][2], document the field in [the `t` type][3] as `resp_headers: [headers]`.

Then somewhere in my complete mess of tests find the `handle_connect` tests and add a test that confirms you can get to the headers in the `conn` that's passed back. _(You can just confirm that the headers that are required to upgrade the connection are available)_

That would be more than enough for a PR or if you don't get around to it ping me and remind me on Monday and I will make time.

[1]: https://github.com/Azolo/websockex/blob/master/lib/websockex.ex#L818-L835
[2]: https://github.com/Azolo/websockex/blob/master/lib/websockex/conn.ex#L13-L24
[3]: https://github.com/Azolo/websockex/blob/master/lib/websockex/conn.ex#L56-L65
